vars:
- buildingnet_root: citydata/buildingnet

stages:
  render_images:
    cmd: python render_images.py ${buildingnet_root}/meshes ${buildingnet_root}/images
    deps:
    - render_images.py
    - ${buildingnet_root}/meshes
    outs:
    - ${buildingnet_root}/images
  close_meshes:
    cmd: python close_meshes.py ${buildingnet_root}/meshes ${buildingnet_root}/meshes_closed
    deps:
    - close_meshes.py
    - bin/manifold
    outs:
    - ${buildingnet_root}/meshes_closed
  generate_voxels:
    cmd: python generate_voxels.py ${buildingnet_root}/meshes_closed ${buildingnet_root}/voxels
    deps:
    - generate_voxels.py
    - ${buildingnet_root}/meshes_closed
    outs:
    - ${buildingnet_root}/voxels
  generate_occupancy_points:
    cmd: python generate_occupancy_points.py ${buildingnet_root}/meshes_closed ${buildingnet_root}/occpancy_points
    deps:
    - generate_occupancy_points.py # TODO: Create this file
    - ${buildingnet_root}/meshes_closed
    outs:
    - ${buildingnet_root}/occpancy_points
  